FROM node:14-alpine AS build

WORKDIR /app

COPY app /app

RUN npm install && npm run build

FROM node:14-alpine
WORKDIR /app

RUN npm install -g webserver.local

COPY --from=build /app/build ./build

EXPOSE 3000

CMD webserver.local -d ./build
